holunda-io/camunda-bpm-taskpool

- .travis.yml
- camunda-engine-client/pom.xml
- camunda-engine-plugin/pom.xml
- datapool/datapool-api/pom.xml
- datapool/datapool-core/pom.xml
- datapool/datapool-sender/pom.xml
- datapool/pom.xml
- examples/h2/pom.xml
- examples/pom.xml
- examples/process-application/pom.xml
- examples/tasklist-angular/pom.xml
- examples/tasklist-api/pom.xml
- examples/tasklist-backend/pom.xml
- examples/tasklist-react/pom.xml
- pom.xml
- taskpool/pom.xml
- taskpool/taskpool-api/pom.xml
- taskpool/taskpool-collector/pom.xml
- taskpool/taskpool-core/pom.xml
- taskpool/taskpool-sender/pom.xml
- view/pom.xml
- view/simple/pom.xml
- view/view-api/pom.xml
> 1.0.3-SNAPSHOT

- camunda-engine-plugin/pom.xml
- camunda-engine-plugin/src/main/kotlin/io/holunda/camunda/taskpool/plugin/CamundaEventingEnginePlugin.kt
- camunda-engine-plugin/src/main/kotlin/io/holunda/camunda/taskpool/plugin/CamundaEventingProperties.kt
- camunda-engine-plugin/src/main/kotlin/io/holunda/camunda/taskpool/plugin/EnableCamundaSpringEventing.kt
- camunda-engine-plugin/src/main/kotlin/io/holunda/camunda/taskpool/plugin/PublishDelegateParseListener.kt
- camunda-engine-plugin/src/main/kotlin/io/holunda/camunda/taskpool/plugin/PublishHistoryEventHandler.kt
- camunda-engine-plugin/src/test/kotlin/io/holunda/camunda/taskpool/plugin/CamundaEventingITest.kt
- camunda-engine-plugin/src/test/kotlin/io/holunda/camunda/taskpool/plugin/TestApplication.kt
- camunda-engine-plugin/src/test/resources/application-itest.yml
- camunda-engine-plugin/src/test/resources/test.bpmn
- view/view-api/src/main/kotlin/query/TaskWithDataEntriesForIdQuery.kt
> feat: implement historic event handler in engine plugin

- examples/process-forms/Dockerfile
- examples/process-forms/pom.xml
- examples/tasklist-angular/Dockerfile
- examples/tasklist-angular/pom.xml
- examples/tasklist-react/pom.xml
- view/cockpit/frontend/Dockerfile
- view/cockpit/frontend/pom.xml
I updated the npm version to the latest lts version.
> chore: update node to latest lts version (10.15.1)

- view/cockpit/frontend/src/app/components/taskeventlist/taskeventlist.component.html
- view/cockpit/frontend/src/app/components/taskeventlist/taskeventlist.component.scss
- view/cockpit/frontend/src/app/components/taskeventlist/taskeventlist.component.ts
> bugfix: display complex data like payload and candidate groups properly

- pom.xml
> chore: bump axon version

- pom.xml
Clarified / beautified the camunda version switch in pom.xml, use 7.12.7-ee (for security reasons ;)
> Merge camunda-version-switch to develop

- docs/src/orchid/resources/changelog/2.0/2.0.12.ad
- pom.xml
Testet within my customer project, works fine. 
Solves #265
> Update to Axon 4.4

- engine/variable-serializer/src/test/kotlin/VariableSerializerTest.kt
> fix: fix flaky test

- view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/Converters.kt
- view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/MongoViewService.kt
- view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/data/DataEntryConverterTest.kt
Probably overlooked in refactoring
> fix: change package of Converters.kt

- view/simple/src/main/kotlin/io/holunda/polyflow/view/simple/service/SimpleTaskPoolService.kt
- view/simple/src/test/kotlin/io/holunda/polyflow/view/TaskWithDataEntriesTest.kt
- view/simple/src/test/kotlin/io/holunda/polyflow/view/simple/service/SimpleTaskPoolServiceTest.kt
- view/view-api/src/main/kotlin/TaskWithDataEntries.kt
… by avoiding unnecessarily iterating in nested loops
fixes #392
> improve performance of simple view 

- view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/SpecificationExt.kt
- view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/data/DataEntryRepository.kt
- view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/SpecificationTest.kt
Add JpaSpecification for entryId, entryType and type for filtering DataEntries
> Add JpaSpecification for entryId, entryType and type for filtering DataEntries

- pom.xml
- view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/MongoViewService.kt
- view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/TaskPoolMongoViewConfiguration.kt
- view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/TaskPoolMongoViewProperties.kt
- view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/task/TaskChangeTracker.kt
- view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/task/TaskDocument.kt
- view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/task/TaskRepository.kt
- view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/task/TaskWithDataEntriesRepositoryExtensionImpl.kt
- view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/TaskPoolMongoTestContext.kt
- view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/service/PolyflowMongoServiceRetryTest.kt
- view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/service/TaskChangeTrackerTest.kt
- view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/task/TaskDocumentBuilder.kt
- view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/task/TaskRepositoryExtensionImplITest.kt
> Delay task deletion in Mongo View

- integration/common/taskpool-sender/src/main/kotlin/io/holunda/polyflow/taskpool/sender/gateway/AxonCommandListGateway.kt
> do not make internal, let users create instances

- bom/parent/pom.xml
- integration/camunda-bpm/taskpool-collector/src/main/kotlin/io/holunda/polyflow/taskpool/collector/CamundaTaskpoolCollectorProperties.kt
- integration/common/datapool-sender/src/main/kotlin/io/holunda/polyflow/datapool/DataEntrySenderProperties.kt
- integration/common/tasklist-url-resolver/src/main/kotlin/io/holunda/polyflow/urlresolver/TasklistUrlProperties.kt
- view/form-url-resolver/src/main/kotlin/io/holunda/polyflow/urlresolver/FormUrlResolverProperties.kt
- view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/PolyflowJpaViewProperties.kt
- view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewServiceTaskITest.kt
- view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/TaskPoolMongoViewProperties.kt
- activated annotation processing
- added more java doc to provide more information about properties
> feature: add metadata generation to allow properties auto-completion in IDEA, fix #564

- view/view-api/src/main/kotlin/QueryGatewayExt.kt
> Change response type for query extension functions

- view/view-api/pom.xml
- view/view-api/src/main/kotlin/DataEntry.kt
- view/view-api/src/main/kotlin/Task.kt
- view/view-api/src/main/kotlin/query/data/DataEntriesForUserQuery.kt
- view/view-api/src/main/kotlin/query/data/DataEntriesQuery.kt
- view/view-api/src/test/kotlin/DataEntryTest.kt
- view/view-api/src/test/kotlin/TaskTest.kt
- view/view-api/src/test/kotlin/query/data/DataEntriesForUserQueryTest.kt
- view/view-api/src/test/kotlin/query/data/DataEntriesQueryTest.kt
> Do not use public byLazy delegates properties in api data classes

- bom/parent/pom.xml
- view/jpa/pom.xml
- view/view-api/pom.xml
Without this we cannot use jackson serialization, see https://github.com/holixon/axon-gateway-extension/issues/114
> Update gav for axon-gateway-extension 0.1.0

- view/view-api-client/src/main/kotlin/QueryGatewayExt.kt
> make revision parameters nullable

- core/taskpool/taskpool-core/pom.xml
- view/view-api/pom.xml
> bugfix: change scope for test dependencies, fix #680

- core/datapool/datapool-core/src/main/kotlin/io/holunda/polyflow/datapool/core/DataPoolCoreAxonConfiguration.kt
- core/datapool/datapool-core/src/main/kotlin/io/holunda/polyflow/datapool/core/DataPoolCoreConfiguration.kt
- core/datapool/datapool-core/src/main/kotlin/io/holunda/polyflow/datapool/core/DataPoolProperties.kt
- core/datapool/datapool-core/src/main/kotlin/io/holunda/polyflow/datapool/core/DeletionStrategyValue.kt
- core/datapool/datapool-core/src/main/kotlin/io/holunda/polyflow/datapool/core/EnablePolyflowDataPool.kt
- core/datapool/datapool-core/src/main/kotlin/io/holunda/polyflow/datapool/core/business/DataEntryAggregate.kt
- core/datapool/datapool-core/src/test/kotlin/io/holunda/polyflow/datapool/core/DataPoolCoreDeletionStrategyConfigurationTest.kt
- core/datapool/datapool-core/src/test/kotlin/io/holunda/polyflow/datapool/core/business/DataEntryAggregateFirstEventOnlyEventSourcingRepositoryITest.kt
- core/datapool/datapool-core/src/test/kotlin/io/holunda/polyflow/datapool/core/itest/TestApplication.kt
- core/taskpool/taskpool-core/src/main/kotlin/io/holunda/polyflow/taskpool/core/TaskPoolCoreConfiguration.kt
- integration/camunda-bpm/springboot-starter/src/test/kotlin/TaskpoolStarterITest.kt
- view/jpa/pom.xml
> bugfix: flip the value in deletion strategy configuration, wrote tests for configuration

- core/datapool/datapool-core/src/main/kotlin/io/holunda/polyflow/datapool/core/DataPoolCoreAxonConfiguration.kt
- core/taskpool/taskpool-api/src/main/kotlin/io/holunda/camunda/taskpool/api/task/CamundaTaskEventType.kt
- core/taskpool/taskpool-api/src/main/kotlin/io/holunda/camunda/taskpool/api/task/EngineTaskCommandSorter.kt
- core/taskpool/taskpool-api/src/main/kotlin/io/holunda/camunda/taskpool/api/task/EngineTaskCommands.kt
- core/taskpool/taskpool-event/src/main/kotlin/io/holunda/camunda/taskpool/mapper/task/TaskFactoryMethods.kt
- docs/reference-guide/components/camunda-taskpool-collector.md
- integration/camunda-bpm/taskpool-collector/src/main/kotlin/io/holunda/polyflow/taskpool/DelegateTaskExtensions.kt
- integration/camunda-bpm/taskpool-collector/src/main/kotlin/io/holunda/polyflow/taskpool/collector/CamundaTaskpoolCollectorProperties.kt
- integration/camunda-bpm/taskpool-collector/src/main/kotlin/io/holunda/polyflow/taskpool/collector/task/TaskEventCollectorService.kt
- integration/camunda-bpm/taskpool-collector/src/main/kotlin/io/holunda/polyflow/taskpool/collector/task/enricher/ProcessVariablesTaskCommandEnricher.kt
- integration/camunda-bpm/taskpool-collector/src/test/kotlin/io/holunda/polyflow/taskpool/itest/TaskCollectorITest.kt
- integration/common/taskpool-sender/src/main/kotlin/io/holunda/polyflow/taskpool/sender/task/accumulator/EngineTaskCommandProjectionErrorDetector.kt
- integration/common/taskpool-sender/src/main/kotlin/io/holunda/polyflow/taskpool/sender/task/accumulator/ProjectingCommandAccumulator.kt
- integration/common/taskpool-sender/src/main/kotlin/io/holunda/polyflow/taskpool/sender/task/accumulator/SimpleEngineTaskCommandIntentDetector.kt
> Fixed update listener and assignment handling. Remove formKey from update commands

- bom/parent/pom.xml
- docs/reference-guide/components/view-api.md
- integration/camunda-bpm/taskpool-job-sender/pom.xml
- view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/SpecificationExt.kt
- view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/task/TaskRepository.kt
- view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/task/TaskRepositoryITest.kt
Implementation of more filter in JPA views.
> more jpa filtering

- bom/parent/pom.xml
- view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/MongoViewService.kt
- view/view-api/src/main/kotlin/ComponentLike.kt
> Add marker interface to open components

- bom/parent/pom.xml
- core/bus-jackson/src/test/kotlin/io/holunda/polyflow/view/query/data/DataEntryQueriesDeserializationTest.kt
- core/datapool/datapool-core/src/test/kotlin/io/holunda/polyflow/datapool/core/itest/TestApplication.kt
- core/spring-utils/src/main/kotlin/io/holunda/polyflow/spring/ApplicationNameBeanPostProcessor.kt
- core/spring-utils/src/test/kotlin/io/holunda/polyflow/datapool/DataEntrySenderProperties.kt
- core/spring-utils/src/test/kotlin/io/holunda/polyflow/spring/ApplicationNameBeanPostProcessorTest.kt
- core/taskpool/taskpool-core/src/test/kotlin/io/holunda/polyflow/taskpool/core/TestApplication.kt
- pom.xml
- fix reflective property access, fix #908 
- upgrade to Spring-Boot 3.1.5 
- upgrade Axon Framework BOM to 4.9
> Fixes reflective access

- integration/camunda-bpm/taskpool-collector/src/main/kotlin/io/holunda/polyflow/taskpool/collector/task/enricher/ProcessVariablesCorrelator.kt
- view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/SpecificationExt.kt
- view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/task/TaskRepository.kt
- view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewServiceTaskITest.kt
> Allow ot overwrite correlateVariables method of the ProcessVariableCorrelator

- view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/service/TaskChangeTrackerTest.kt
> fix: avoid "The Publisher returned by the supplier is null" exception

- integration/common/variable-serializer/src/main/kotlin/VariableSerializer.kt
- integration/common/variable-serializer/src/test/kotlin/JsonPathWithValueTest.kt
- integration/common/variable-serializer/src/test/kotlin/VariableSerializerTest.kt
- view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/payload/PayloadAttribute.kt
> 988 serialization of list variables

- core/datapool/datapool-api/src/main/kotlin/io/holunda/camunda/taskpool/api/business/DataEntryCommands.kt
- core/datapool/datapool-core/src/main/kotlin/io/holunda/polyflow/datapool/core/business/DataEntryAggregate.kt
- core/datapool/datapool-core/src/test/kotlin/io/holunda/polyflow/datapool/core/business/DataEntryAggregateTest.kt
- core/datapool/datapool-event/src/main/kotlin/io/holunda/camunda/taskpool/api/business/BusinessEvents.kt
- core/datapool/datapool-event/src/main/kotlin/io/holunda/camunda/taskpool/api/business/Mappers.kt
- integration/common/datapool-sender/src/main/kotlin/io/holunda/polyflow/datapool/sender/DataEntryCommandSender.kt
- integration/common/datapool-sender/src/main/kotlin/io/holunda/polyflow/datapool/sender/SimpleDataEntryCommandSender.kt
- view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewDataEntryService.kt
- view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/data/ConverterExt.kt
- view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/data/DataEntryEventHandler.kt
- view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewServiceDataEntryITest.kt
- view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/TestFixtures.kt
- view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/data/ConverterExtKtTest.kt
- view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/Converters.kt
- view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/MongoViewService.kt
- view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/service/PolyflowStages.kt
- view/simple/src/main/kotlin/io/holunda/polyflow/view/simple/service/Converters.kt
- view/simple/src/main/kotlin/io/holunda/polyflow/view/simple/service/SimpleDataEntryService.kt
- view/simple/src/main/kotlin/io/holunda/polyflow/view/simple/service/SimpleTaskPoolService.kt
- view/simple/src/test/kotlin/io/holunda/polyflow/view/simple/service/ConvertersKtTest.kt
- Adds a new command to anonymize Data Entries
closes #1011
> Anonymize Data Entries

- view/jpa/pom.xml
improved generation, fix #1007
> Metadata generation for JPA view
